[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bteam-utils"
version = "0.1.0"
dependencies = [
    "pandas",
    "holidays",
]

[tool.setuptools]
packages = ["bteam_utils"]
